fix: Use Object.prototype.hasOwnProperty.call instead of direct method calling. (#176)
Summary:
I encountered an error while trying to use with latest twilio javascript sdk:
https://media.twiliocdn.com/sdk/js/chat/v3.3/twilio-chat.min.js

error :
```
Uncaught (in promise) TypeError: t.hasOwnProperty is not a function
    at e (recoil.js:122)
    at e (recoil.js:122)
    at e (recoil.js:122)
    at e (recoil.js:122)
    at Object.set (recoil.js:626)
    at setNodeValue (recoil.js:379)
    at recoil.js:526
    at Object.replaceState (recoil.js:746)
    at recoil.js:525
    at Object.trace (recoil.js:337)
```

My Code Snippets:

```ts
const [client, setClient] = useRecoilState(twilioClientState);
...
twilio.Chat.Client.create(token).then((client) => {
        setClient(client); // <- this raise an error.
});
```

And it seems that an error occurred while trying to deep freeze object.
Because some object that not inherit `Object` prototype pass thorough `typeof` checking.

Minimal reproducible example:

```js
const nonObject = Object.create(null);
nonObject["hello"] = "world";
nonObject.hello
=> "world"
typeof nonObject
=> "object"
nonObject === null
=> false
nonObject.hasOwnProperty
=> undefined
Object.prototype.hasOwnProperty.call(mapLike, 'hello')
=> true
```
Pull Request resolved: https://github.com/facebookexperimental/Recoil/pull/176

Reviewed By: mondaychen

Differential Revision: D21746790

Pulled By: drarmstr

fbshipit-source-id: 6e95ff7e816668c0777a1ec14490cb64a849b5d8